import { User } from "src/app/pages/shared/interfaces/user";

export class TaskModel {
  public _id!: string; // generated by mongoDB
  public title!: string;
  public description!: string;
  public createdAt!: Date; // generated by mongoDB
  public updatedAt!: Date; // generated by mongoDB
  public reward!: number;
  public participants!: string[];
  public type!: "daily" | "weekly" | "onetime";
  public difficulty!: number;
  public deadline!: string;
  public completed!: boolean;

  constructor(model?: any) {
    Object.assign(this, model);
  }

}
