export class ItemModel {
  public _id!: string;
  public createdAt!: Date; // generated by mongoDB
  public updatedAt!: Date; // generated by mongoDB
  public name!: string;
  public description!: string;
  public image!: string;
  public price!: number;
  public selected!: boolean

  constructor(model?: any) {
    Object.assign(this, model);
  }
}

