import { User } from "src/app/pages/shared/interfaces/user";

export class UserModel {
  public _id!: string; // generated by mongoDB
  public name!: string;
  public currency!: string;
  public createdAt!: Date; // generated by mongoDB
  public updatedAt!: Date; // generated by mongoDB
  public parent!: boolean;
  public quests!: Task[];

  constructor(model?: any) {
    Object.assign(this, model);
  }

}
