import { Item } from "src/app/pages/shared/interfaces/item";

export class ShopModel {
    public _id!: string;
    public createdAt!: Date; // generated by mongoDB
    public updatedAt!: Date; // generated by mongoDB
    public name!: string;
    public owner!: string;
    public items!: Item[];
  
    constructor(model?: any) {
      Object.assign(this, model);
    }
  }
  
  